files:
  - path: ./prompt/selection.txt
    commit_hash: c0d60848bd57a5610bc8a7ee697ad5d4abf0f69f
    content: |
      base-A
  - path: ./prompt/rerank.txt
    commit_hash: c0d60848bd57a5610bc8a7ee697ad5d4abf0f69f
    content: |
      base-A
